services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    container_name: gara-backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks: # ADICIONADO
      - app-network
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: gara
      DB_USERNAME: gara
      DB_PASSWORD: gara

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: gara-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/public
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: gara-frontend
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Força o monitoramento de arquivos no Windows
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0", "--poll", "30000"] # Importante para o Docker
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: gara-db
    environment:
      POSTGRES_DB: gara
      POSTGRES_USER: gara
      POSTGRES_PASSWORD: gara
    ports:
      - "5432:5432"
    volumes:
      - gara_db_data:/var/lib/postgresql/data
    networks:
      - app-network # CORRIGIDO (era app_network)

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network: 
    driver: bridge

volumes:
  gara_db_data:
    driver: local