services:
  gara_backend:
    image: 
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.5-trixie'
    # volumes:
    #   - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
